import {afterEach,describe,it,expect,vi} from 'vitest';
import {VoiceEditor} from './voiceEditor';
import type {DesignSystem} from '../designer/api';
afterEach(()=>vi.unstubAllGlobals());
const ds:DesignSystem={id:'brand',name:'Brand',source_file:'x',slide_size_emu:[1,1],assets:[],patterns:[],tokens:{colors:[{hex:'123456',role:'text',source:'usage',share:1},{hex:'abcdef',role:'background',source:'usage',share:1}],fonts:[{family:'Georgia',role:'body',share:1}],type_scale:[{role:'display',size_pt:36,share:1}],margins:{left:.05,top:.05,right:.05,bottom:.05}}};
describe('editor services',()=>{
 it('applies theme to existing and newly created components and published HTML',()=>{const e=new VoiceEditor();e.add('title','Title');e.applyDesign(ds);expect(e.selected).toMatchObject({font:'Georgia',color:'#123456',size:48});expect(e.current.background).toBe('#abcdef');expect(e.add('text','Body').color).toBe('#123456');expect(e.slide().html).toContain('font-family:Georgia');});
 it('dictates into selected object and switches modes without adding mode names',async()=>{const e=new VoiceEditor();e.add('title','Plan');await e.interpret('Диктую текст',()=>{});await e.interpret('запуска',()=>{});expect(e.selected?.text).toBe('Plan запуска');await e.interpret('Управляю слайдом',()=>{});expect(e.mode).toBe('control');expect(e.current.components).toHaveLength(1);});
 it('does not insert unknown requests as slide text when model is down',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false,json:async()=>({detail:'Модель недоступна'})}));const e=new VoiceEditor();await e.interpret('Слайд про доставку',()=>{});expect(e.current.components).toHaveLength(0);expect(e.notice).toContain('Модель недоступна');});
 it('discards a delayed plan if the document changed',async()=>{let resolve!:(v:unknown)=>void;vi.stubGlobal('fetch',()=>new Promise(r=>{resolve=r;}));const e=new VoiceEditor();const work=e.interpret('Слайд о доставке',()=>{});e.add('text','Manual');resolve({ok:true,json:async()=>({commands:['добавь заголовок Delivery'],clarification:''})});await work;expect(e.current.components).toHaveLength(1);expect(e.notice).toContain('изменился');});
 it('replaces the original image even if selection changes during search',async()=>{const e=new VoiceEditor();const target=e.add('image','Old');vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({items:[{url:'https://upload.wikimedia.org/test.jpg',title:'New',source:'https://commons.wikimedia.org/test',author:'Author',license:'CC BY'}]})}));await e.images('courier',false,()=>{});e.add('text','Other');e.pickImage(1);expect(target.url).toContain('test.jpg');expect(target.attribution).toContain('CC BY');expect(e.slide().notes).toContain('Author');});
});
