import {it,expect,vi,afterEach} from 'vitest';
import {VoiceEditor} from './voiceEditor';
afterEach(()=>vi.unstubAllGlobals());
it.skipIf(process.env.RUN_EDITOR_LIVE!=='1')('edits an actual deck through local Ollama',async()=>{
 const e=new VoiceEditor();
 vi.stubGlobal('localStorage',{setItem:()=>{}});
 const nativeFetch=globalThis.fetch;
 vi.stubGlobal('fetch',async (...args:Parameters<typeof fetch>)=>{const r=await nativeFetch(...args);if(String(args[0]).endsWith('/intent'))console.log('Plan:',JSON.stringify(await r.clone().json()));return r;});
 const theme=await fetch('http://localhost:8090/design-systems/voicedeck-design-system');
 if(theme.ok)e.applyDesign(await theme.json());
 const say=async(text:string)=>{await e.interpret(text,()=>{});console.log(text,e.notice);};
 await say('Добавь заголовок «План запуска» и две карточки: «Продукт» и «Продажи». Карточки размести рядом под заголовком.');
 expect(e.current.components.filter(c=>c.kind==='card')).toHaveLength(2);
 const card=e.current.components.find(c=>c.text.includes('Продукт'))!;const x=card.x;
 await say('Сдвинь карточку «Продукт» на 30 пикселей вправо и сделай её текст жирным.');
 expect(card.x).toBe(x+30);expect(card.bold).toBe(true);
 await say('Переименуй карточку «Продажи» в «Маркетинг».');
 expect(e.current.components.some(c=>c.text==='Маркетинг')).toBe(true);
 await say('Создай новый слайд и добавь таблицу: заголовки Товар и Цена; строка Книга и 500; строка Ручка и 100.');
 expect(e.document.pages).toHaveLength(2);expect(e.current.components.find(c=>c.kind==='table')?.rows).toContainEqual(['Книга','500']);
 await say('В таблице измени цену книги на 900, остальные ячейки сохрани.');
 expect(e.current.components.find(c=>c.kind==='table')?.rows).toContainEqual(['Книга','900']);
 await say('Перейди на первый слайд и удали карточку «Маркетинг».');
 expect(e.document.index).toBe(0);expect(e.current.components.filter(c=>c.kind==='card')).toHaveLength(1);
 e.undo();expect(e.document.pages[0].components.filter(c=>c.kind==='card')).toHaveLength(2);
 await say('Перейди на первый слайд. Преврати карточку «Продукт» в обычный текст. Размер текста 32, цвет синий #2563eb, слева 100, сверху 200, ширина 400, высота 150.');
 expect(e.document.pages[0].components).toHaveLength(3);
 expect(e.document.pages[0].components.find(c=>c.text==='Продукт')).toMatchObject({kind:'text',size:32,color:'#2563eb',x:100,y:200,width:400,height:150});
},600000);
