import React,{useRef,useState,useEffect} from 'react';
import {VoiceEditor,Component} from './voiceEditor';
import {contentHtml,mediaUrl} from './componentContent';
import {applyPlan} from './editorOperations';
import {BASE_URL} from '../designer/api';
import {Type,Heading,Image as ImageIcon,Square,Table,ChartColumn,LayoutPanelTop,Hash,Trash2,Bold,Italic,Lock,Unlock,Upload,Plus,Minus,Group,Ungroup,AlignLeft,AlignCenter,AlignRight,ArrowUpToLine,ArrowDownToLine} from 'lucide-react';
import './editor.css';

export function EditorCanvas({editor,edit}:{editor:VoiceEditor;edit:(f:()=>void)=>void}){
 const canvas=useRef<HTMLDivElement>(null);
 const [width,setWidth]=useState(800);
 const drag=useRef<{id:string;x:number;y:number;targets:{id:string;x:number;y:number;width:number;height:number}[];resize:boolean;recorded:boolean}|null>(null);
 useEffect(()=>{const el=canvas.current;if(!el)return;const observer=new ResizeObserver(()=>setWidth(el.clientWidth));observer.observe(el);return()=>observer.disconnect();},[]);
 const selected=editor.selected;
 const update=(patch:Partial<Component>)=>{if(selected)edit(()=>applyPlan(editor,{operations:[{op:'update',targets:editor.selectedIds,props:patch}],clarification:'',summary:'Свойства изменены'}));};
 const run=(op:string,value?:string)=>edit(()=>applyPlan(editor,{operations:[{op,value}],clarification:'',summary:'Изменения применены'}));
 function down(e:React.PointerEvent,id:string,resize=false){
  e.preventDefault();e.stopPropagation();
  edit(()=>editor.selectMany(e.shiftKey?[...editor.selectedIds,id]:editor.selectedIds.includes(id)?editor.selectedIds:[id]));
  const targets=editor.current.components.filter(c=>editor.selectedIds.includes(c.id));
  if(targets.some(c=>c.locked))return;
  drag.current={id,x:e.clientX,y:e.clientY,targets:targets.map(c=>({id:c.id,x:c.x,y:c.y,width:c.width,height:c.height})),resize,recorded:false};e.currentTarget.setPointerCapture(e.pointerId);
 }
 async function upload(file?:File){
  if(!file||!selected)return;const target=selected.id,page=editor.current.id;
  try{if(file.size>8*1024*1024)throw Error('Изображение больше 8 МБ');const response=await fetch(BASE_URL+'/editor/assets',{method:'POST',body:file,signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw Error(data.detail);if(editor.current.id!==page)throw Error('Вернитесь на исходный слайд');edit(()=>editor.update(target,{url:data.url}));}
  catch(error){edit(()=>{editor.notice=String(error);});}
 }
 return <div className="component-editor">
  <div>
   <div className="component-toolbar"><button className="button" title="Номера элементов" aria-label="Номера элементов" aria-pressed={editor.showNumbers} onClick={()=>edit(()=>{editor.showNumbers=!editor.showNumbers;})}><Hash size={18}/></button>{(['title','text','card','shape','image','table','chart'] as const).map((kind,i)=>{const Icon=[Heading,Type,LayoutPanelTop,Square,ImageIcon,Table,ChartColumn][i];const label=['Заголовок','Текст','Карточка','Фигура','Изображение','Таблица','Диаграмма'][i];return <button className="button" key={kind} title={label} aria-label={'Добавить '+label.toLowerCase()} onClick={()=>edit(()=>applyPlan(editor,{operations:[{op:'add',props:{kind,text:'',...(kind==='table'?{rows:[['Название','Значение'],['','']],width:600,height:240}:kind==='chart'?{labels:['A','B'],values:[0,0],width:600,height:360}: {})}}],clarification:'',summary:'Элемент создан'}))}><Icon size={18}/></button>;})}</div>
   <div ref={canvas} className="component-canvas" style={{background:editor.current.background,backgroundImage:editor.current.backgroundUrl?`url("${mediaUrl(editor.current.backgroundUrl)}")`:undefined,backgroundSize:'100% 100%'}} aria-label="Холст слайда" onPointerDown={()=>edit(()=>editor.selectMany([]))}>
    {!editor.current.components.length&&<p className="canvas-empty">Пустой слайд</p>}
    {editor.current.components.map(c=><div key={c.id} role="button" tabIndex={0} aria-label={`Номер ${c.voiceNumber}. ${c.kind}: ${c.text}`} aria-pressed={editor.selectedIds.includes(c.id)} className={`canvas-component ${editor.selectedIds.includes(c.id)?'selected':''}`} style={{left:`${c.x/12.8}%`,top:`${c.y/7.2}%`,width:`${c.width/12.8}%`,height:`${c.height/7.2}%`,color:c.color,background:c.kind==='chart'?'transparent':c.fill,fontFamily:c.font??'Arial',fontSize:c.size*width/1280,fontWeight:(c.bold??(c.kind==='title'))?700:400,fontStyle:c.italic?'italic':'normal',textAlign:c.align,transform:`rotate(${c.rotation??0}deg)`,opacity:c.opacity??1,borderRadius:(c.radius??0)*width/1280,border:`${(c.borderWidth??0)*width/1280}px solid ${c.borderColor??'transparent'}`,padding:c.kind==='card'?16*width/1280:0}}
     onKeyDown={e=>{if(e.key==='Enter')edit(()=>editor.select(c.id));}}
     onPointerDown={e=>down(e,c.id)} onPointerMove={e=>{const d=drag.current;if(!d||d.id!==c.id)return;let dx=(e.clientX-d.x)*1280/width,dy=(e.clientY-d.y)*1280/width;if(!dx&&!dy)return;edit(()=>{if(!d.recorded){editor.checkpoint();d.recorded=true;}if(d.resize){const origin=d.targets.find(t=>t.id===d.id)!;editor.update(d.id,{width:origin.width+dx,height:origin.height+dy},false);}else{dx=Math.max(-Math.min(...d.targets.map(t=>t.x)),Math.min(dx,...d.targets.map(t=>1280-t.x-t.width)));dy=Math.max(-Math.min(...d.targets.map(t=>t.y)),Math.min(dy,...d.targets.map(t=>720-t.y-t.height)));d.targets.forEach(t=>editor.update(t.id,{x:t.x+dx,y:t.y+dy},false));}});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
     <div style={{width:'100%',height:'100%',overflow:'hidden',pointerEvents:'none'}} dangerouslySetInnerHTML={{__html:contentHtml(c)}}/>
     {selected?.id===c.id&&!c.locked&&<span className="resize-handle" aria-label="Изменить размер" onPointerDown={e=>down(e,c.id,true)}/>}
    </div>)}
    {editor.showNumbers&&editor.current.components.map(c=><button key={c.id} className="voice-number" aria-label={`Выбрать номер ${c.voiceNumber}`} aria-pressed={editor.selectedIds.includes(c.id)} style={{left:`${c.x/12.8}%`,top:`${c.y/7.2}%`}} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();edit(()=>editor.select(c.id));}}>{c.voiceNumber}</button>)}
   </div>
  </div>
  <aside className="component-properties"><h3>{selected?'Элемент '+selected.voiceNumber:'Слайд '+(editor.document.index+1)}</h3>{selected?<>
   <div className="component-toolbar"><button title="Блокировка" aria-label="Блокировка" aria-pressed={!!selected.locked} onClick={()=>update({locked:!selected.locked})}>{selected.locked?<Lock size={17}/>:<Unlock size={17}/>}</button><button title="Жирный" aria-label="Жирный" aria-pressed={!!selected.bold} onClick={()=>update({bold:!selected.bold})}><Bold size={17}/></button><button title="Курсив" aria-label="Курсив" aria-pressed={!!selected.italic} onClick={()=>update({italic:!selected.italic})}><Italic size={17}/></button>{(['left','center','right'] as const).map((align,i)=>{const Icon=[AlignLeft,AlignCenter,AlignRight][i];return <button key={align} title={['По левому краю','По центру','По правому краю'][i]} aria-label={['По левому краю','По центру','По правому краю'][i]} onClick={()=>update({align})}><Icon size={17}/></button>;})}</div>
   <label>Текст<textarea key={selected.id+selected.text} defaultValue={selected.text} onBlur={e=>{if(e.target.value!==selected.text)update({text:e.target.value});}}/></label>
   {(['x','y','width','height','size'] as const).map((key,i)=><label key={key}>{['Слева','Сверху','Ширина','Высота','Размер текста'][i]}<input type="number" value={Math.round(selected[key])} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value))update({[key]:key==='size'?Math.max(12,Math.min(120,value)):value});}}/></label>)}
   <label>Цвет текста<input type="color" value={selected.color} onChange={e=>update({color:e.target.value})}/></label>
   <label>Заливка<input type="color" value={selected.fill==='transparent'?'#ffffff':selected.fill} onChange={e=>update({fill:e.target.value})}/></label>
   <label>Без заливки<input type="checkbox" checked={selected.fill==='transparent'} onChange={e=>update({fill:e.target.checked?'transparent':'#ffffff'})}/></label>
   <label>Шрифт<select value={selected.font??'Arial'} onChange={e=>update({font:e.target.value})}>{[...new Set([selected.font??'Arial','Arial','Georgia','Verdana','Times New Roman'])].map(f=><option key={f}>{f}</option>)}</select></label>
   <label>Поворот<input aria-label="Поворот" type="number" min={-360} max={360} value={selected.rotation??0} onChange={e=>update({rotation:Math.max(-360,Math.min(360,Number(e.target.value)))})}/></label>
   <label>Непрозрачность<input aria-label="Непрозрачность" type="range" min={0} max={1} step={.05} value={selected.opacity??1} onChange={e=>update({opacity:Number(e.target.value)})}/></label>
   <label>Скругление<input type="number" min={0} max={360} value={selected.radius??0} onChange={e=>update({radius:Math.max(0,Math.min(360,Number(e.target.value)))})}/></label>
   <label>Рамка<input type="color" value={selected.borderColor??'#17141f'} onChange={e=>update({borderColor:e.target.value,borderWidth:selected.borderWidth||1})}/><input aria-label="Толщина рамки" type="number" min={0} max={20} value={selected.borderWidth??0} onChange={e=>update({borderWidth:Math.max(0,Math.min(20,Number(e.target.value)))})}/></label>
   {selected.kind==='image'&&<><label className="button"><Upload size={17}/>Изображение<input aria-label="Загрузить изображение" className="editor-file-input" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0])}/></label><label>Размещение<select value={selected.fit??'contain'} onChange={e=>update({fit:e.target.value as 'contain'|'cover'})}><option value="contain">Целиком</option><option value="cover">Заполнить</option></select></label></>}
   {selected.kind==='table'&&<div className="editor-table-data">{(selected.rows??[]).map((row,ri)=><div key={ri}>{row.map((cell,ci)=><input key={ci} aria-label={`Ячейка ${ri+1}, ${ci+1}`} value={cell} maxLength={1000} onChange={e=>edit(()=>applyPlan(editor,{operations:[{op:'table_cell',targets:[selected.id],row:ri+1,column:ci+1,value:e.target.value}],clarification:'',summary:'Ячейка изменена'}))}/>)}</div>)}<div className="component-toolbar"><button title="Добавить строку" aria-label="Добавить строку" onClick={()=>run('table_row_add')}><Plus size={16}/></button><button title="Удалить строку" aria-label="Удалить строку" onClick={()=>run('table_row_delete')}><Minus size={16}/></button></div></div>}
   {selected.kind==='chart'&&<div className="editor-chart-data">{(selected.labels??[]).map((label,i)=><div key={i}><input aria-label={`Подпись ${i+1}`} value={label} onChange={e=>update({labels:selected.labels!.map((s,j)=>j===i?e.target.value:s)})}/><input aria-label={`Значение ${i+1}`} type="number" min={0} value={selected.values?.[i]??0} onChange={e=>update({values:selected.values!.map((n,j)=>j===i?Math.max(0,Number(e.target.value)):n)})}/></div>)}<button title="Добавить значение" aria-label="Добавить значение" disabled={(selected.labels?.length??0)>=20} onClick={()=>update({labels:[...selected.labels??[],''],values:[...selected.values??[],0]})}><Plus size={16}/></button><button title="Удалить значение" aria-label="Удалить значение" onClick={()=>update({labels:selected.labels?.slice(0,-1),values:selected.values?.slice(0,-1)})}><Minus size={16}/></button></div>}
   <div className="component-toolbar"><button title="Сгруппировать" aria-label="Сгруппировать" onClick={()=>run('group')}><Group size={17}/></button><button title="Разгруппировать" aria-label="Разгруппировать" onClick={()=>run('ungroup')}><Ungroup size={17}/></button><button title="На передний план" aria-label="На передний план" onClick={()=>run('layer','front')}><ArrowUpToLine size={17}/></button><button title="На задний план" aria-label="На задний план" onClick={()=>run('layer','back')}><ArrowDownToLine size={17}/></button><button title="Удалить элемент" aria-label="Удалить элемент" onClick={()=>run('delete')}><Trash2 size={17}/></button></div>
  </>:<><label>Фон<input type="color" value={editor.current.background} onChange={e=>edit(()=>{editor.checkpoint();editor.current.background=e.target.value;})}/></label><label>Заметки<textarea value={editor.current.notes??''} onChange={e=>edit(()=>applyPlan(editor,{operations:[{op:'notes',value:e.target.value}],clarification:'',summary:'Заметки обновлены'}))}/></label></>}</aside>
 </div>;
}
