import {describe,it,expect} from 'vitest';
import {VoiceEditor} from './voiceEditor';
import {applyPlan,Operation} from './editorOperations';
import {deckHtml} from './editorExport';
const run=(e:VoiceEditor,operations:Operation[])=>applyPlan(e,{operations,clarification:'',summary:'Done'});
describe('validated document operations',()=>{
 it('selects a slide by ID and gives newly created dark cards readable text',()=>{const e=new VoiceEditor();const first=e.current.id;run(e,[{op:'slide_add'},{op:'slide_select',targets:[first]},{op:'add',props:{kind:'card',fill:'#17141f',text:'Readable'}}]);expect(e.document.index).toBe(0);expect(e.selected?.color).toBe('#ffffff');});
 it('transfers objects and exports every slide without changing current selection',()=>{const e=new VoiceEditor();const a=e.add('title','First');run(e,[{op:'slide_add'},{op:'add',props:{kind:'title',text:'Second'}},{op:'slide_select',index:1},{op:'transfer',targets:[a.id],index:2}]);expect(e.current.components).toHaveLength(0);expect(e.document.pages[1].components).toHaveLength(2);const before=JSON.stringify(e.document);expect(deckHtml(e)).toContain('Second');expect(deckHtml(e).match(/<iframe /g)).toHaveLength(2);expect(JSON.stringify(e.document)).toBe(before);});
 it('creates and precisely edits objects in one undoable transaction',()=>{const e=new VoiceEditor();run(e,[{op:'add',alias:'a',props:{kind:'card',text:'Delivery',x:100,y:200,width:300,height:200}},{op:'move',targets:['a'],props:{x:40,y:-20}},{op:'update',targets:['a'],props:{bold:true,fill:'#123456',rotation:15,opacity:.7}}]);expect(e.selected).toMatchObject({x:140,y:180,bold:true,fill:'#123456',rotation:15,opacity:.7});e.undo();expect(e.current.components).toHaveLength(0);e.redo();expect(e.current.components).toHaveLength(1);});
 it('rolls back the entire plan when a target is missing',()=>{const e=new VoiceEditor();expect(()=>run(e,[{op:'add',props:{text:'test'}},{op:'delete',targets:['missing']}])).toThrow();expect(e.current.components).toHaveLength(0);expect(e.undoStack).toHaveLength(0);});
 it('rejects unsafe properties and malformed chart data atomically',()=>{const e=new VoiceEditor();expect(()=>run(e,[{op:'add',props:{kind:'chart',labels:['A'],values:[1,2]}}])).toThrow();expect(()=>run(e,[{op:'add',props:{url:'javascript:alert(1)'}}])).toThrow();expect(e.current.components).toHaveLength(0);});
 it('groups, moves, layers, and deletes components',()=>{const e=new VoiceEditor();const a=e.add('card','A'),b=e.add('card','B');const x=a.x;run(e,[{op:'group',targets:[a.id,b.id]},{op:'move',targets:[a.id],props:{x:10}},{op:'layer',targets:[a.id],value:'back'}]);expect(a.x).toBe(x+10);expect(b.group).toBe(a.group);run(e,[{op:'delete',targets:[a.id]}]);expect(e.current.components).toHaveLength(0);e.undo();expect(e.current.components).toHaveLength(2);});
 it('edits tables and renders escaped content',()=>{const e=new VoiceEditor();run(e,[{op:'add',props:{kind:'table',rows:[['Name','Price'],['<script>','900']]}}]);expect(e.slide().html).toContain('&lt;script&gt;');expect(e.slide().html).toContain('900');});
 it('duplicates, reorders and removes slides with unique IDs',()=>{const e=new VoiceEditor();e.add('title','First');run(e,[{op:'slide_duplicate',index:1},{op:'slide_move',index:1}]);expect(e.document.pages).toHaveLength(2);expect(e.document.pages[0].components[0].id).not.toBe(e.document.pages[1].components[0].id);run(e,[{op:'slide_delete',index:2}]);expect(e.document.pages).toHaveLength(1);expect(()=>run(e,[{op:'slide_delete',index:1}])).toThrow();});
});
