import {describe,it,expect,vi} from 'vitest';
import {VoiceEditor} from './voiceEditor';
describe('voice editor',()=>{
 it('restores components and images from browser storage',()=>{const cache=new Map<string,string>();vi.stubGlobal('localStorage',{setItem:(k:string,v:string)=>cache.set(k,v),getItem:(k:string)=>cache.get(k)??null});try{const a=new VoiceEditor();a.input('Добавь заголовок План');a.input('Создай три карточки');a.save();const b=new VoiceEditor();b.restore();expect(b.document).toEqual(a.document);}finally{vi.unstubAllGlobals();}});
 it('separates dictation and commands and edits the last component',()=>{const e=new VoiceEditor();e.input('План запуска. Команда: сделай это заголовком');expect(e.current.components).toHaveLength(1);expect(e.selected?.kind).toBe('title');expect(e.selected?.text).toBe('План запуска');e.input('Команда: заголовок крупнее');expect(e.selected?.size).toBe(48);});
 it('preserves literal commands and rejects unknown commands',()=>{const e=new VoiceEditor();e.input('Дословно: команда помогает команде');expect(e.selected?.text).toBe('команда помогает команде');e.input('Команда: полетели');expect(e.current.components).toHaveLength(1);expect(e.notice).toContain('не распознана');});
 it('undoes deletion and redoes with stable component identities',()=>{const e=new VoiceEditor();e.input('Первый');e.input('Добавь пункт Второй');const id=e.selected!.id;e.input('Команда: удали второй пункт');expect(e.current.components).toHaveLength(1);e.undo();expect(e.current.components[1].id).toBe(id);e.redo();expect(e.current.components).toHaveLength(1);});
 it('keeps the published snapshot unchanged during editing',()=>{const e=new VoiceEditor();e.input('Заметка');expect(e.published).toBeNull();e.input('Команда: покажи залу');const html=e.published!.html;e.input('Дополнение');expect(e.published!.html).toBe(html);e.input('Команда: новый слайд');expect(e.current.components).toHaveLength(0);e.undo();expect(e.current.components).toHaveLength(1);expect(e.selected?.text).toBe('Заметка Дополнение');});
 it('creates cards, targets an ordinal, changes fill and geometry',()=>{const e=new VoiceEditor();e.input('Добавь заголовок План запуска');e.input('Создай три карточки');e.input('Первую назови Подготовка');e.input('Сделай вторую фиолетовой');const cards=e.current.components.filter(c=>c.kind==='card');expect(cards).toHaveLength(3);expect(cards[0].text).toBe('Подготовка');expect(cards[1].fill).toBe('#7654ff');const y=cards[1].y;e.input('Перемести выше');expect(cards[1].y).toBe(y-40);e.undo();expect(e.selected?.y).toBe(y);});
 it('clamps movement and resizing to canvas boundaries',()=>{const e=new VoiceEditor();e.input('Добавь фигуру');e.update(e.selected!.id,{x:2000,y:-500,width:3000,height:0});expect(e.selected).toMatchObject({x:0,y:0,width:1280,height:40});});
 it('adds image placeholders and escapes dictated HTML',()=>{const e=new VoiceEditor();e.input('Команда: добавь справа изображение склада');expect(e.selected?.side).toBe('right');expect(e.selected?.kind).toBe('image');e.input('<script>alert(1)</script>');expect(e.slide().html).not.toContain('<script>');});
});
